/**
 * Branded string type for task short IDs.
 * Format: TSK-NNNN (e.g., TSK-0001, TSK-0042)
 * Brand prevents accidental plain string assignment.
 */
export type ShortId = string & { readonly __brand: 'ShortId' };

/**
 * Lifecycle statuses for a task.
 * Note: 'completed' is only set by historical import (Feature 38)
 * or reconciliation cache writes (Feature 13). It is never set
 * directly by user actions in the normal task lifecycle.
 */
export enum TaskStatus {
  Draft = 'draft',
  Approved = 'approved',
  Rejected = 'rejected',
  Pushed = 'pushed',
  Completed = 'completed',
}

/**
 * Which consumer created or last edited a task or task version.
 */
export enum TaskSource {
  Agent = 'agent',
  UI = 'ui',
  Terminal = 'terminal',
}

/**
 * Priority level for a task.
 */
export enum TaskPriority {
  Low = 'low',
  Medium = 'medium',
  High = 'high',
  Critical = 'critical',
}

/**
 * Reference to an external project management system.
 * This pattern replaces Asana-specific fields (asana_task_id,
 * asana_workspace_id, asana_project_id) to support multiple PM tools
 * (Asana, Monday.com, Jira, etc.) without schema changes.
 *
 * Stored as JSONB in the tasks table.
 */
export interface ExternalRef {
  /** Identifies the PM system. e.g., "asana", "monday", "jira" */
  system: string;
  /** Task ID in the external system. Null until pushed. */
  externalId: string | null;
  /** Deep link to the task in the external system. Null until pushed. */
  externalUrl: string | null;
  /** Project ID within the workspace. Null if unassigned. */
  projectId: string | null;
  /** Workspace/organization ID in the external system. Null if unassigned. */
  workspaceId: string | null;
}

/**
 * Structured description generated by the Mastra intake agent.
 * All three sections are required — the agent must populate each one.
 * Stored as JSONB in the database (JSONB-compatible structure).
 */
export interface TaskDescription {
  /** Background and purpose of the task. */
  taskContext: string;
  /** Supplementary context from the source transcript. */
  additionalContext: string;
  /** Array of specific deliverables or acceptance criteria. */
  requirements: string[];
}

/**
 * A task in the iExcel system.
 * Primary output of the intake workflow (Workflow A).
 */
export interface NormalizedTask {
  id: string;
  shortId: ShortId;
  clientId: string;
  transcriptId: string | null;
  status: TaskStatus;
  title: string;
  description: TaskDescription;
  assignee: string | null;
  priority: TaskPriority;
  /** ISO 8601 duration string. e.g., "PT2H30M" for 2h 30m. */
  estimatedTime: string | null;
  /** ISO 8601 date string. e.g., "2026-03-15". */
  dueDate: string | null;
  scrumStage: string;
  tags: string[];
  /** Null until the task is pushed to an external PM system. */
  externalRef: ExternalRef | null;
  /** UUID of the user who approved the task. Null until approved. */
  approvedBy: string | null;
  approvedAt: string | null;
  pushedAt: string | null;
  createdAt: string;
  updatedAt: string;
}

/**
 * Immutable snapshot of a task's editable fields at a point in time.
 * Created on every edit. Version 1 is the agent-generated original.
 */
export interface TaskVersion {
  id: string;
  taskId: string;
  version: number;
  title: string;
  description: TaskDescription;
  estimatedTime: string | null;
  /** Null for agent-authored versions. */
  editedBy: string | null;
  source: TaskSource;
  createdAt: string;
}

export interface CreateTaskRequest {
  clientId: string;
  transcriptId?: string;
  title: string;
  description: TaskDescription;
  assignee?: string;
  priority?: TaskPriority;
  estimatedTime?: string;
  dueDate?: string;
  scrumStage?: string;
  tags?: string[];
}

export interface UpdateTaskRequest {
  title?: string;
  description?: Partial<TaskDescription>;
  assignee?: string;
  priority?: TaskPriority;
  estimatedTime?: string;
  dueDate?: string;
  scrumStage?: string;
  tags?: string[];
}
